### ISSUE TITLE
RStudio not loading project with rig 0.5.0 with renv

### ISSUE THREAD

**Issue by PMassicotte** [r-lib/rig#100]
I installed the latest version of rig (0.5.0). When using `rig rstudio renv.lock`, it opens RStudio with the proper version of R registered in the `renv` lock file. However, the project is not loaded. Hopefully, this animated GIF clearly shows the issue.

![Peek 2022-06-20 10-59](https://user-images.githubusercontent.com/4519221/174630248-7d2afb0c-6016-444f-a24b-a08cdba65899.gif)

Please let me know if I can provide further details.

Thank you in advance,
Phil

**Comment by gaborcsardi** [comment]
So should rig use the `.Rproj` file that is in the same directory as `renv.lock`? Is it possible to have multiple `.Rproj` files in that directory?

**Comment by gaborcsardi** [comment]
Seems like Rstudio behaves differently in different OSes:
- on Windows the newer versions (from 2023.06.1) work correctly. Versions before that are wrong.
- macOS is completely wrong, it tries to open the path that rig passes to it as a file
- Linux: TODO
