### ISSUE TITLE
Stable link for latest release

### ISSUE THREAD

**Issue by eliocamp** [r-lib/rig#102]
I don't know if github allows this, but it would be nice to have a link to the latest release so that installation instructions don't need to change every time there's a new version. (I'm creating installation instructions for students and it would be nice not having to update them at the beginning of each semester).

**Comment by gaborcsardi** [comment]
Good idea. I created a `latest` tag and release and also renamed the installers: https://github.com/r-lib/rig/releases/tag/latest
