### ISSUE TITLE
Uninstalling rig

### ISSUE THREAD

**Issue by csgillespie** [r-lib/rig#105]
How do I uninstall rig and go back to my original set-up? (Linux)

---

I'm having odd issues with R things and I'm trying to debug.

**Comment by gaborcsardi** [comment]
For debugging, you can just ignore rig, and install R the old way. rig does not actively do anything if you don't call it. It does update the R installation after a `rig add`, but it you install R without rig, it will not interfere with it.

If you want to make sure that nothing calls rig, remove the `/usr/local/bin/rig` file.

If you want to clean up absolutely everything, remove these files within `/usr/local/` (keep the directories, though if they are not empty).
```
❯ tar tzf rig-linux-latest.tar.gz
bin/
bin/rig
share/
share/zsh/
share/zsh/site-functions/
share/zsh/site-functions/_rig
share/bash-completion/
share/bash-completion/completions/
share/bash-completion/completions/rig.bash
```

**Comment by csgillespie** [comment]
Did rig install R in /opt/R/4.X.X/bin/R ?

**Comment by gaborcsardi** [comment]
On Linux rig installs R there, yes:

```r
ubuntu@foo:~$ rig list --json
[
  {
    "name": "3.4.4",
    "default": false,
    "version": "3.4.4",
    "path": "/opt/R/3.4.4",
    "binary": "/opt/R/3.4.4/bin/R"
  },
  {
    "name": "3.5.3",
    "default": false,
    "version": "3.5.3",
    "path": "/opt/R/3.5.3",
    "binary": "/opt/R/3.5.3/bin/R"
  },
...
```
