### ISSUE TITLE
Problem with Secondary Repos 

### ISSUE THREAD

**Issue by ddsjoberg** [r-lib/rig#107]
Apologies in advance that I don't have simple reproducible example to include here.

Today I installed R 4.2.1 with rig for Windows using the "Latest" release link, and I am now experiencing an issue with the my secondary repos.

I use the RStudio RSPM repo to install CRAN packages, and I also have my institution's RSPM linked as well (called MSK_RSPM). These repos were setup before the installation, and appear to still be set up (see screengrab below)

![image](https://user-images.githubusercontent.com/26774684/178590247-3d9e85d3-a992-4099-aa65-5f30a1973e76.png)

The strange part is that when I open a fresh RStudio session, the repos are set to the CRAN cloud mirror, the RStudio RSPM is listed, but my MSK_RSPM is no where to be seen. I've removed it and added it back again...but it doesn't appear to be recognized by RStudio any longer.

```
R version 4.2.1 (2022-06-23 ucrt) -- "Funny-Looking Kid"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> getOption("repos")
                                           RSPM                                            CRAN 
"https://packagemanager.rstudio.com/all/latest"                   "https://cloud.r-project.org" 
```

Thank you!

**Comment by gaborcsardi** [comment]
If you want to manage repositories in RStudio, then I suggest you tell rig not to set the default repos:

```
rig add --without-cran-mirror --without-rspm
```

**Comment by ddsjoberg** [comment]
Ahh, gotcha. I didn't realize that these would suppress the RStudio settings. I uninstalled 4.2.1 and re-installed with those options and everything works with the secondary repos again.

Thank you!

**Comment by gaborcsardi** [comment]
Yeah, it seems that if `repos` is already set, then RStudio will not touch it. That's what that warning means.
