### ISSUE TITLE
Rig changing user permissions on existing R library?

### ISSUE THREAD

**Issue by jimjam-slam** [r-lib/rig#109]
Hi there! I'm just giving `rig` a whirl and really enjoying it so far. However, after I installed it, I opened my existing R installation, and I could no longer install packages to my existing library at `/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library` due to a permission issue.

Checking that folder, all of the subfolders now belong to `root:admin`. If I re-open R with `sudo`, I can install packages again.

I definitely didn't need `sudo` to install packages before I installed `rig` - I just installed and updates packages yesterday. Is it possible that `rig` inadvertently changed the permissions on my library folder

**Comment by jimjam-slam** [comment]
Ah, I only just clocked this comment: https://github.com/r-lib/rig/issues/80#issuecomment-1144542156

Is there a warning message on installation of rig that you're changing the permissions of an existing library folder?

**Comment by gaborcsardi** [comment]
Yeah, a warning would be nice indeed when changing permissions of existing R versions. Or rig probably should not change the permissions of the other R versions at all.
