### ISSUE TITLE
Installed R versions not found after installing rig

### ISSUE THREAD

**Issue by MxNl** [r-lib/rig#116]
Hello,

just installed and used rig for the first time. 
When using `rig list`, my previously installed R version 4.1.2 is not found.
Am I missing sth?

I am on Linux XXX 4.15.0-163-generic #171-Ubuntu SMP Fri Nov 5 11:55:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Thanks a lot!

**Comment by gaborcsardi** [comment]
rig installs R into `/opt/R`. If you installed R from your distribution, that version is completely independent of rig.
