### ISSUE TITLE
Menu bar doesn't appear on Mac 

### ISSUE THREAD

**Issue by sjmgarnier** [r-lib/rig#118]
OS: macOS Monterey 12.5.1
Hardware: Macbook Pro 14 inch (Apple M1 Pro)
RIG version: 0.5.1 (installed via Homebrew)

Symptoms: no menu bar when running `open -a Rig` or opening the Rig.app application. CLI tool seems to work fine, however.

**Comment by gaborcsardi** [comment]
Can you check if it is running?
```
ps aux | grep Rig
```

If it is running, then maybe you have too many menu bar apps and it does not fit, so macOS omits it or it is under the bezel on a new M1 mac? 

If it is not running, then can you start it with `/Applications/Rig.app/Contents/MacOS/Rig` to see any error messages?

**Comment by sjmgarnier** [comment]
You're right. It was hiding behind the stupid camera notch. Sorry about the bother, I should have thought about it. Maybe an improvement would be to replace the text with an icon.

**Comment by gaborcsardi** [comment]
> Maybe an improvement would be to replace the text with an icon.

Maybe, but it is hard to show `R-4.2-arm64` on an icon.

**Comment by sjmgarnier** [comment]
I meant a simple icon for Rig in the menu bar that shows the R version/gives access to the menu when clicked (sort of like what Rswitch looks like). Or at least an option to display a small icon instead of the full R version. For instance, I do not need to know at all times which R version is the current default on my machine and I'm happy to be able to check it with a single click whenever I need to know.

**Comment by gaborcsardi** [comment]
Got it. An easy way to do that now is to use RSwitch: https://github.com/r-lib/rig#-faq

**Comment by grantmcdermott** [comment]
Just got bitten by this myself. 

+1 on a a single tray icon (with drop down) if that's on the roadmap at some point.

P.S. Very much enjoying rig and the wide distro support has been super helpful for some of our team projects running on the, uh, more venerable linux cloud instances. Thanks Gabor!

**Comment by gaborcsardi** [comment]
https://github.com/r-lib/rig/issues/190
