### ISSUE TITLE
Cannot install R version 4.0.* on Mac

### ISSUE THREAD

**Issue by mattwarkentin** [r-lib/rig#123]
Hi,

I am new to using `rig` for my R management. I am not sure why I cannot successfully run:
```zsh
rig add 4.0.5
```
or 
```zsh
rig add 4.0
```

I get the following error:
```
[ERROR] Cannot find a download url for R version 4.0.5, arm64
```

Is it because I am using a new Mac with an M1 chip?

**Comment by gaborcsardi** [comment]
R 4.0.5 does not work on arm64 macs. You can install the x86_64 version of R, though:
```
rig add 4.0 -a x86_64
```

**Comment by cathblatter** [comment]
@gaborcsardi  - could this code be added to the README? I find myself coming back to this closed issue regularly to look it up...(I'd be happy to create a PR if wished?)

**Comment by gaborcsardi** [comment]
Well, it is in `rig add --help`.
