### ISSUE TITLE
`rig system add-pak` repo points to nonexistent site?

### ISSUE THREAD

**Issue by netique** [r-lib/rig#126]
```
[INFO] Installing pak for R 4.2-arm64
[INFO] > WARNING: ignoring environment value of R_HOME
[INFO] > WARNING: ignoring environment value of R_HOME
[INFO] > Warning in install.packages("pak", repos = sprintf("https://r-lib.github.io/p/pak/stable/%s/%s/%s",  :
[INFO] >   'lib = "/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library"' is not writable
[INFO] > Error in install.packages("pak", repos = sprintf("https://r-lib.github.io/p/pak/stable/%s/%s/%s",  : 
[INFO] >   unable to install packages
[INFO] > Execution halted
[ERROR] Failed to install pak for R 4.2-arm64: command ["/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/R", "--vanilla", "-s", "-e", "                install.packages(\'pak\', repos = sprintf(\'https://r-lib.github.io/p/pak/stable/%s/%s/%s\', .Platform$pkgType, R.Version()$os, R.Version()$arch))            "] exited with code 1
```

The URL resolves to `https://r-lib.github.io/p/pak/stable/mac.binary.big-sur-arm64/darwin20/aarch64`, but I can see nothing there. Note I run this on released Ventura.

**Comment by gaborcsardi** [comment]
The URL is fine, but the library it is trying to install to is not.

It seems like you are running this from within R? E.g. RStudio terminal? Can you try to run it from a real terminal?

**Comment by netique** [comment]
I'm sorry for not enclosing the rig version info - it's the up-to-date 0.5.2, installed with homebrew. I thought I was running it from the proper zsh terminal, but maybe you are right and I was using the Terminal tab in RStudio. Now it seems to work for me.

**Comment by gaborcsardi** [comment]
Well, it should (ideally) work from RStudio terminal as well, so this is definitely a bug, thanks for reporting it. But I am glad that it works now.
