### ISSUE TITLE
Open renv defined version from menu bar app

### ISSUE THREAD

**Issue by vitallish** [r-lib/rig#131]
It would be great if there was an option that automatically opened the renv defined R version when opening a project from the menu bar item. Currently you can choose `Default` or a specific R version. Specifically, could there be another option that is something like 'renv or Default' which open the renv defined version if available - otherwise the Default version?

**Comment by gaborcsardi** [comment]
I guess the `Default` could just open the renv specified one for renv projects? If that version is installed? And if it is not installed, then open the default one? renv will issue a warning for the latter case, so maybe rig does not need to do that.

**Comment by vitallish** [comment]
Yeah that would be ideal
