### ISSUE TITLE
R version switch does not work in new Rstudio release

### ISSUE THREAD

**Issue by AGSCL** [r-lib/rig#134]

**Comment by gaborcsardi** [comment]
I am afraid that more details are needed for this. What OS? What rig version? What RStudio version? What command does not work exactly?

**Comment by AGSCL** [comment]
HI. 

Windows 10, RIG -- The R Installation Manager 0.5.2, Rstudio 2022.12.0 Build 353.
When I first installed this Rstudio version,  the Choose R Installation window poped-up, I checked "Use machine's default 64-bit version of R". Then, when I ran "rig rstudio 4.1.2" it only started the r version 4.0.2 (automatically put by default)

**Comment by AGSCL** [comment]
Also I tried running "make-links"  subcommand but I did not find where CMD created links

**Comment by cs-tum** [comment]
I can confirm this issue on Win10. Previous RStudio-2022.07.2-576 works well with rig v0.5.2, but RStudio-2022.12.0-353 always starts with the R version selected in Rstudio's own GUI, ignoring the R version invoked using rig. 

The command would be for example "rig rstudio 4.2.2" versus "rig rstudio 3.6.3".

**Comment by gaborcsardi** [comment]
Reported in rstudio: https://github.com/rstudio/rstudio/issues/12545

**Comment by AGSCL** [comment]
It is part of the release notes, i guess: "Updated RStudio Desktop installer on Windows to detect running RStudio by process name. (#10588)" (https://posit.co/download/rstudio-desktop/). Is there any workaround to this problem?

**Comment by gaborcsardi** [comment]
@AGSCL that seems to be about the installer, so unrelated to this issue. To this issue, AFAIK the only workaround is to install an earlier version of RStudio.

**Comment by AGSCL** [comment]
As today, this issue persist. Hope that the next Rstudio version resolves it

**Comment by gaborcsardi** [comment]
Yeah, the situation is still the same, so maybe we could work around it in rig.

Apparently, from 2022.12.0 RStudio uses a `config.json` file to store the selected R version. So if we change that before starting RStudio, and then restore the file after, that could work.

IDK if there are any caveats. E.g. if RStudio does update this file on startup, and then we restore the original file, then the updates by RStudio will be lost, and this also creates a race condition potentially.

Alternatively, I could send a patch to RStudio to look up the R executable from an environment variable, just like on Unix.

**Comment by gaborcsardi** [comment]
This should work now with the dev version, release is coming soon! I tested a bunch of RStudio versions, and they are all ok.
