### ISSUE TITLE
rig update equivalent?

### ISSUE THREAD

**Issue by Alanocallaghan** [r-lib/rig#135]
Is there an equivalent of `rig update release` to run I guess the equivalent `rig rm release && rig add release` if there is a new version available? Or is there a more elegant way to do this with keyword versions (just release and devel so far, I think)

Sorry if this is explained in the docs, I've looked a couple of times but may just be missing it.

**Comment by gaborcsardi** [comment]
There isn't an equivalent, as the main focus is to install multiple versions at the same time. So I suggest you install the new version and make it the default. You can still keep the old version, just in case some project would not work with the new version.

Or yeah, run `rig rm release && rig add release`, that should work if you have a `release` version installed.

**Comment by Alanocallaghan** [comment]
Thanks, the keyword versions are the only situation you'd want `rig update` to do anything anyways so this makes sense
