### ISSUE TITLE
RIG is not set in the run directory

### ISSUE THREAD

**Issue by acastillom24** [r-lib/rig#139]
A few weeks ago when running rig, the working directory was set to the run directory, now rstudio starts in the home directory.

rstudio version:
![image](https://user-images.githubusercontent.com/81824205/213932276-dd6c5cae-85a6-44fd-b91e-f7abd10298a3.png)

**Comment by gaborcsardi** [comment]
I am not entirely sure what you mean. Maybe this is a duplicate of #134?

**Comment by acastillom24** [comment]
Hi gaborcsardi,
![image](https://user-images.githubusercontent.com/81824205/213958593-3e9f8152-2b62-4f3f-a882-d59706b3ce91.png)
I am working in the directory {D:\Proyectos\GIT\R}, rstudio was previously started with this same directory. But now it starts in the home directory.
![image](https://user-images.githubusercontent.com/81824205/213958960-d4dce9a0-ab2b-47ba-959b-4e8d53ae4d17.png)

**Comment by gaborcsardi** [comment]
Bye "previously" previously, do you mean a previous version of rig, or a previous version of RStudio? I suspect the latter.

**Comment by acastillom24** [comment]
thanks, I just reinstalled version 2022.07 - Spotted Wakerobin and it works correctly. On the other hand, one of the interesting things about using version 2022.12 is: Highlight R function calls.

**Comment by gaborcsardi** [comment]
I fixed this on Windows, but so far could not find a way to set the working directory on macOS and Linux.

**Comment by gaborcsardi** [comment]
OK, now works on all OSes, with newer RStudio versions (>= 2023.06.0).
