### ISSUE TITLE
Install rig using winget

### ISSUE THREAD

**Issue by jaredlander** [r-lib/rig#143]
This is completely a feature request. I've been using winget to install software on Windows, including R and RStudio. It's native to windows so I think a lot of people are more comfortable with it than scoop or chocolatey. Could you make rig available on winget?

**Comment by eitsupi** [comment]
I created a PR (not yet merged) microsoft/winget-pkgs#108337

**Comment by jaredlander** [comment]
Thanks! That's awesome. Looking forward to it working.

**Comment by cderv** [comment]
Thanks @eitsupi  ! I guess you can add to the README here now under all other Windows installation ways. 👍

**Comment by gaborcsardi** [comment]
Thanks all, I have just added this to the README.
