### ISSUE TITLE
`rig resolve release` resolves to wrong version

### ISSUE THREAD

**Issue by jabenninghoff** [r-lib/rig#150]
`rig resolve release` fails to resolve to R 4.3.0, which was released on 2023-04-21.

```sh
% rig resolve -a x86_64 release
4.2.3 https://cran.r-project.org/bin/macosx/base/R-4.2.3.pkg
```

This only affects `x86_64`:

```sh
% rig resolve -a arm64 release
4.3.0 https://cran.r-project.org/bin/macosx/big-sur-arm64/base/R-4.3.0-arm64.pkg
```

This is likely due to the change in directory structure; the x86 4.3 package is no longer in <https://cloud.r-project.org/bin/macosx/base/> but instead in <https://cloud.r-project.org/bin/macosx/big-sur-x86_64/base/>.

**Comment by gaborcsardi** [comment]
Because there is no x86_64 build for R 4.3.0 yet, see https://cran.r-project.org/bin/macosx/base/

**Comment by gaborcsardi** [comment]
Actually, there is one at https://cran.r-project.org/bin/macosx/big-sur-x86_64/base/

**Comment by gaborcsardi** [comment]
OK, try again please, this should be fixed now:
```
❯ rig resolve -a x86_64 release
4.3.0 https://cran.r-project.org/bin/macosx/big-sur-x86_64/base/R-4.3.0-x86_64.pkg
```

Thanks for reporting!

Btw. you'll need the latest rig 0.5.3 release to install this properly.

**Comment by jabenninghoff** [comment]
Yep, I have 0.5.3 installed, `rig resolve` now works, thanks!
