### ISSUE TITLE
Homebrew tap's installer places rig under `/usr/local` on ARM macOS

### ISSUE THREAD

**Issue by baggiponte** [r-lib/rig#154]
On ARM, homebrew's prefix is `/opt/homebrew`, but `rig` is installed under `/usr/local/` (which is the prefix for Intel Macs). Does this happen by choice? I tried to look for the install formula but could not find it, but I could help if you want.

**Comment by baggiponte** [comment]
Thank you for the prompt reply! Sorry for being inaccurate (edited the title accordingly). Indeed, since the tap uses the original installer it does not make sense to install under `/opt/homebrew`. Do you plan to distribute `rig` as a formula too - from this same tap?

**Comment by gaborcsardi** [comment]
No, I am not planning on doing that. I am not even sure what the benefit would be.

Btw. you don't need to install both the arm and x86_64 versions on an arm64 mac, the arm version can install all R versions, including x86_64 builds.

**Comment by baggiponte** [comment]
> Btw. you don't need to install both the arm and x86_64 versions on an arm64 mac, the arm version can install all R versions, including x86_64 builds.

Indeed! I did not mean to install both, but I wanted to ask since setting up homebrew on ARM Macs (with `brew shellenv`) does not add `/usr/local` to `$PATH` as it would on Intel Macs, thus users might not find `rig`.

Anyway, thanks for clarifying!

**Comment by baggiponte** [comment]
Sorry for the late reply. On my ARM mac it is not and if my memory serves me well, on my old Intel mac `/usr/local/bin` was added to my `$PATH` because I was using `brew shellenv` that did so. I will dig that back and check.

**Comment by gaborcsardi** [comment]
FWIW I just checked this on a vanilla macOS Monterey VM:
```
admin@admins-Virtual-Machine ~ % echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```
