### ISSUE TITLE
File exists (os error 17) when try to set the default R version

### ISSUE THREAD

**Issue by ifendo** [r-lib/rig#157]
hi,
I got an error like below this one when I try to switch the default R version from 4.2 to 4.1:
![image](https://github.com/r-lib/rig/assets/10232854/036a3a68-17a9-46c5-8585-354a34d6c8f7)

I am using Mac with macOS version 12.6.5 and Chip Apple M1 Pro. I thought this one was similar to #124  , but as suggested, I created this new issue for future reference. Thank you very much.

Best Regards,
ifendo

**Comment by gaborcsardi** [comment]
What's the output of
```
ls -l /Library/Frameworks/R.framework/Versions
```
?

**Comment by ifendo** [comment]
thank you, here is the output: 
![ls-output](https://github.com/r-lib/rig/assets/10232854/e2705ddf-b34b-4a72-8a89-4c2fac39d8f9)

**Comment by gaborcsardi** [comment]
Yes, currently only users in the admin group can change the default version.

**Comment by ifendo** [comment]
thank you for confirmation, so I will close this.
