### ISSUE TITLE
Debian 12 support?

### ISSUE THREAD

**Issue by eitsupi** [r-lib/rig#162]
Rig does not seem supporting Debian 12 now.

**Comment by gaborcsardi** [comment]
There are no R builds for Debian 12 yet: https://github.com/rstudio/r-builds/pull/166

**Comment by gaborcsardi** [comment]
We have now Debian 12 R builds (x86_64, arm64 still building), but this will still need a rig release first.

**Comment by gaborcsardi** [comment]
Now released.

**Comment by JosiahParry** [comment]
running `rig system detect-platform` on `debian:bookworm-slim` results in: 

```
root@3e739a9536e7:/usr/src/app# rig system detect-platform
Detected platform:
Architecture: aarch64
OS:           linux
Distribution: debian
Version:      12
PPM support:  false
```

However, I believe PPM now supports Debian binaries: https://p3m.dev/client/#/repos/cran/setup

<img width="493" alt="Image" src="https://github.com/user-attachments/assets/bed00b15-3808-4113-a306-f685e9769f51" />

<img width="313" alt="Image" src="https://github.com/user-attachments/assets/2147d8e5-0a54-4e43-997a-df5cbd658ad7" />

would it be possible to update rig to use PPM with debian 12?

**Comment by eitsupi** [comment]
Isn't it because the platform is aarch64?
https://github.com/r-lib/rig/blob/2b0678339bb997005251c057e8ec7af4c8c28ffa/src/linux.rs#L754-L757

**Comment by JosiahParry** [comment]
Ah, yes. Good catch. 

```r
install.packages("dplyr", repos = "https://p3m.dev/cran/__linux__/bookworm/latest")
```
resulted in source installations
