### ISSUE TITLE
Can't run rig on Ubuntu 18.04.6 LTS

### ISSUE THREAD

**Issue by Easillorga** [r-lib/rig#164]
Hello

I have some problem when I install rig on Ubuntu 18.04.6 LTS, I can not run it. 

When I am trying, the following error displays : 
`bash: /usr/local/bin/rig: cannot execute binary file: Exec format error`

Here is what I did : 

- Installed amd64 version 
- Checked my Ubuntu Version with `uname -a` which gives me : `Linux vdi 5.4.0-1106-gcp #115~18.04.1-Ubuntu SMP Mon May 22 20:46:39 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
- Tried modifying permissions (even if it was not the problem)
- Checked the file format with `file rig` which shows me : `rig: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, not stripped`. What I am finding a bit strange is that no interpreter is present in the Elf file, is it normal ?

Do you have any clue on how to fix it ?

Thanks in advance,

Easill

**Comment by gaborcsardi** [comment]
You probably installed the arm64 version?

It works fine for me:

```
root@9cad3e8f1092:~# arch
x86_64
root@9cad3e8f1092:~# curl -LO https://github.com/r-lib/rig/releases/download/v0.5.3/rig-linux-0.5.3.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 3950k  100 3950k    0     0  1159k      0  0:00:03  0:00:03 --:--:-- 2122k
root@9cad3e8f1092:~# tar xzf rig-linux-0.5.3.tar.gz -C /usr/local
root@9cad3e8f1092:~# rig ls
* name  version  aliases
------------------------------------------
```

**Comment by Easillorga** [comment]
I will try uninstalling rig and installing the version you sent here.

I will edit this comment once I did it.

**Comment by gaborcsardi** [comment]
You don't need to uninstall everything, just install the correct version, it will overwrite what you have.

Btw. Ubuntu 18.04 is not supported any more, so soon will rig stop supporting it as well, because https://github.com/rstudio/r-builds will stop creating R builds for it.

**Comment by Easillorga** [comment]
Thank you for this information, I will ask if we can upgrade the ubuntu version. 

This installation works fine now. Thank you !

I think I did a mistake with the link provided in the tutorial, I didn't change the version, assuming it would automatically download the latest one. 

Now I only have to correct the pak error : 
`Failed to to install pak for R 4.3.1: Failed to find user HOME`

**Comment by gaborcsardi** [comment]
What tutorial? I didn't know we had a tutorial? :)

**Comment by Easillorga** [comment]
I meant, your "how to install" section !

https://github.com/r-lib/rig#id-installation

There is a small section for installing rig on Ubuntu.

**Comment by gaborcsardi** [comment]
But that is working fine as well:
```
root@dfa3ecb488cd:~# cat /etc/os-release  | grep VERSION=
VERSION="18.04.6 LTS (Bionic Beaver)"

root@dfa3ecb488cd:~# arch
x86_64

root@dfa3ecb488cd:~# curl -Ls https://github.com/r-lib/rig/releases/download/latest/rig-linux-latest.tar.gz | tar xz -C /usr/local

root@dfa3ecb488cd:~# rig --version
RIG -- The R Installation Manager 0.5.3

root@dfa3ecb488cd:~# rig ls
* name  version  aliases
------------------------------------------
```
