### ISSUE TITLE
Be consistent re: default symbolic link on linux

### ISSUE THREAD

**Issue by jennybc** [r-lib/rig#165]
The docs about the symlink for the current default version of R on linux mention two different links in close proximity to one another. It seems like these should be the same?

Says `/usr/local/bin/R`:

https://github.com/r-lib/rig/blob/ad868ce8dee2782a4504fa6e661408d5f4b04e65/src/help-linux.in#L62-L63

Says `/opt/R/current`:

https://github.com/r-lib/rig/blob/ad868ce8dee2782a4504fa6e661408d5f4b04e65/src/help-linux.in#L69-L70

**Comment by jennybc** [comment]
The `linux.rs` file also has mixed use of `/opt/R` vs. `/usr/local/bin` that I find a bit puzzling, but maybe there's more context that I don't have.

**Comment by gaborcsardi** [comment]
It is like this:
```
root@fd239be51682:~# ls -l /usr/local/bin/R
lrwxrwxrwx 1 root root 20 Jun 21 09:18 /usr/local/bin/R -> /opt/R/current/bin/R
root@fd239be51682:~# ls -l /opt/R/current
lrwxrwxrwx 1 root root 12 Jun 21 09:18 /opt/R/current -> /opt/R/4.3.1
```
I guess we don't need to mention `/usr/local/bin/R`. Or don't need to mention either. It does not really matter how it is set, anyway.

**Comment by jennybc** [comment]
OK this helps. Basically the situation is the same on macOS and linux. The `/usr/local/bin/R` symlink is how the outside world accesses the "current version of R", because presumably `/usr/local/bin` is on the PATH.

And `/usr/local/bin/R` points to `/opt/R/current/bin/R` (linux) or `/Library/Frameworks/R.framework/Resources/bin/R` (macOS). This symlink basically never changes.

This symlink target is then part of another network of symlinks that can be manipulated to switch between multiple R installations. I suppose I'll think of *this* as the internal mechanism (i.e. within the realm of R installations) for concretely defining the "current version of R".

On my machine:

```
/usr/local/bin/R -> /Library/Frameworks/R.framework/Resources/bin/R
                    /Library/Frameworks/R.framework/Resources ->
                                                    Versions/Current/Resources
                                                    Versions/Current -> 
                    /Library/Frameworks/R.framework/Versions/4.3-arm64
```

So I guess it makes sense that rig mentions `/usr/local/bin/R` in the context of **getting** the default version of R, but mentions `/opt/R/current` (or `/Library/Frameworks/R.framework/Versions/Current`) in the context of **setting** the default version.
