### ISSUE TITLE
rig creates quick links for non-orthogonal installations

### ISSUE THREAD

**Issue by jennybc** [r-lib/rig#167]
I'm playing around with unholy mixtures of R installations to test something 😬 .

At the moment, I'm on a system where I have done this (in this order):

1. Installed a development version of R from <https://mac.r-project.org> (non-orthogonal installation)
2. Installed the current release from CRAN (after forgetting R installations; non-orthogonal installation; is `Current` installation)
3. Installed `oldrel` with rig (orthogonal installation)

```
~ % rig list
* name        version    aliases
------------------------------------------
  4.2         (R 4.2.3)  oldrel
* 4.3-x86_64  (R 4.3.1)  
  4.4-x86_64  (R 4.4.0) 
```

While installing `oldrel`, I noticed that rig does this:

```
Updating R-* quick links (as needed)
```

And, indeed, I now have symlinks from `/usr/local/bin` to all three versions, including the non-orthogonal ones:

```
~ % ls -laGFh /usr/local/bin/R*
lrwxr-xr-x  1 root  admin    47B 23 Jul 12:41 /usr/local/bin/R@ -> /Library/Frameworks/R.framework/Resources/bin/R
lrwxr-xr-x  1 root  admin    60B 23 Jul 12:41 /usr/local/bin/R-4.2@ -> /Library/Frameworks/R.framework/Versions/4.2/Resources/bin/R
lrwxr-xr-x  1 root  admin    67B 23 Jul 12:41 /usr/local/bin/R-4.3-x86_64@ -> /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/bin/R
lrwxr-xr-x  1 root  admin    67B 23 Jul 12:41 /usr/local/bin/R-4.4-x86_64@ -> /Library/Frameworks/R.framework/Versions/4.4-x86_64/Resources/bin/R
lrwxr-xr-x  1 root  admin    60B 23 Jul 12:41 /usr/local/bin/R-oldrel@ -> /Library/Frameworks/R.framework/Versions/4.2/Resources/bin/R
lrwxr-xr-x  1 root  admin    53B 23 Jul 12:41 /usr/local/bin/Rscript@ -> /Library/Frameworks/R.framework/Resources/bin/Rscript
```

**However**, at this moment, the `R-4.4-x86_64` quick link really isn't usable or safe. Since the concrete installation it points to is non-orthogonal, launching it with the quick link actually launches the `Current` version of R, which is 4.3:

```
~ % R-4.4-x86_64 --vanilla

R version 4.3.1 (2023-06-16) -- "Beagle Scouts"
Copyright (C) 2023 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin20 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> R.version.string
[1] "R version 4.3.1 (2023-06-16)"
```

Of course, launching the rig-installed r-oldrel via quick link **is** safe, because rig made sure the installation is orthogonal:

```
~ % R-4.2 --vanilla

R version 4.2.3 (2023-03-15) -- "Shortstop Beagle"
Copyright (C) 2023 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin17.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> R.version.string
[1] "R version 4.2.3 (2023-03-15)"
```

I think rig probably should not make quick links for non-orthogonal installations.

**Comment by gaborcsardi** [comment]
That would make sense and it is probably also only one case of the many where the non-rig-installed R installations should be left alone. E.g. the coming 
```
rig run --r-version x.y ...
```
will not work properly for them, either.

So maybe rig should just give a warning, telling you to call
```
rig system make-orthogonal
```

There are other modifications as well, that you don't have if you don't use rig to install R. E.g. `rig system setup-user-lib`. Which is needed for `rig library` to work I believe.

In general, I am not sure how much time we want to invest into the cases where half of the R versions are installed by rig, and others not. Maybe it is enough to give a warning to tell them to reinstall R or run the appropriate commands?

**Comment by jennybc** [comment]
> In general, I am not sure how much time we want to invest into the cases where half of the R versions are installed by rig, and others not. Maybe it is enough to give a warning to tell them to reinstall R or run the appropriate commands?

Yeah, I definitely think this is fair. I feel like I have made a lot of similar decisions in usethis, where I just politely decline to operate on setups that were clearly not created with usethis. I think it's fine to emit a warning, maybe with advice, and just refuse to touch such things.
