### ISSUE TITLE
R 3.6.3 macOS installation fails because the download URL moved

### ISSUE THREAD

**Issue by klmr** [r-lib/rig#172]
```
$ rig add -a x86_64 3.6
[INFO] Running `sudo` for adding new R versions. This might need your password.
[INFO] Downloading https://cloud.r-project.org/bin/macosx/R-3.6.3.pkg -> /tmp/rig/x86_64-R-3.6.3.pkg
[ERROR] HTTP error at https://cloud.r-project.org/bin/macosx/R-3.6.3.pkg: HTTP status client error (404 Not Found) for url (https://cloud.r-project.org/bin/macosx/R-3.6.3.pkg)
```

The old bundles are now found on https://cran-archive.r-project.org/.

(I managed to work around this by downloading the installation bundle manually and moving it to `/tmp/rig/x86_64-R-3.6.3.pkg` before rerunning the above command.)

**Comment by gaborcsardi** [comment]
I think this is fixed in the dev tree. For the record, you can also work around these issues with 
```
rig add <URL>
```

**Comment by klmr** [comment]
Ah, marvellous!
