### ISSUE TITLE
Install 4.2.3 replaces 4.2.0

### ISSUE THREAD

**Issue by scholarazwa** [r-lib/rig#173]
Hi,
I would like to have both R 4.2.0 and 4.2.3 installed. However, when I add 4.2.3, it replaces the 4.2.0 version. If I re-install 4.2.0, it replaces the 4.2.3 version. How can I have both installed. Currently 4.3.1 is intact.

➜ rig list     
* name       version    aliases
------------------------------------------
* 4.2-arm64  (R 4.2.3)  
  4.3-arm64  (R 4.3.1)  release

➜ rig list     
* name       version    aliases
------------------------------------------
* 4.2-arm64  (R 4.2.0)  
  4.3-arm64  (R 4.3.1)  release

**Comment by gaborcsardi** [comment]
That would be great, but unfortunately not possible with CRAN's macOS R builds. All 4.2.x builds install to the same place and hardwire a lot of paths to point there, not only in R itself, but even in CRAN's binary R packages.

This is already mentioned in the help:
```
rig add --help
```

```
...
  On macOS rig cannot add multiple R versions from the same minor branch.
  E.g. it is not possible to have R 4.1.1 and R 4.1.2 installed at the
 same time. Adding one of them will automatically remove the other.
...
```

As a workaround, you can keep reinstalling 4.2.0 and 4.2.3 as needed. (They'll use a shared package library by default!) Not great, I agree. 

Or use a virtual machine, e.g. with tart. That should work better.
