### ISSUE TITLE
Windows: list rtools versions

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/rig#18]
Maybe the whole rtools stuff should be a separate command? Or keep it in `rim add`, and have `rim list --rtools` as well?

**Comment by edavidaja** [comment]
FWIWI went looking for it in `rig system`

**Comment by CGMossa** [comment]
There are now many rtools for many versions.. and I think it make sense to make a separate command for it or something.

**Comment by gaborcsardi** [comment]
Closed by 9d68610faff27c37f39ebeb24284bb90644e100f
