### ISSUE TITLE
apt warning during installation - use apt-get

### ISSUE THREAD

**Issue by achubaty** [r-lib/rig#182]
During installation on UBuntu 20.04 I see:

```
[INFO] Running "apt install --reinstall -y -o=Dpkg::Use-Pty=0 /tmp/rig/r-4.2.3_1_amd64.deb"
[INFO] > 
[INFO] > WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
```

Although installation succeeds using the `apt install` command, I believe `apt-get install`  should be used in scripts (see `man apt` section 'SCRIPT USAGE AND DIFFERENCES FROM OTHER APT TOOLS').

I think this is coming from https://github.com/r-lib/rig/blob/69da5c133084fd9ce843189d67b3ec0fbfc9d5d3/src/linux.rs#L126-L130 and should be easy enough to change but I don't know rust at all.

**Comment by gaborcsardi** [comment]
The output redirection does not work with `apt-get`, that's why we are using `apt` here.

We could remove the confusing warning from the output, though.
