### ISSUE TITLE
`--without-sysreqs` is not working?

### ISSUE THREAD

**Issue by eitsupi** [r-lib/rig#184]
```log
#15 70.89 [INFO] Adding /usr/local/bin/R-4.3.1 -> /opt/R/4.3.1/bin/R
#15 70.89 [INFO] Adding R-release alias to R 4.3.1
#15 70.89 [INFO] Setting default CRAN mirror
#15 70.89 [INFO] Setting up P3M
#15 70.89 [INFO] Setting up automatic system requirements installation.
```

I noticed the above log even though I added the `--without-sysreqs` flag in the following location.
https://github.com/rocker-org/devcontainer-features/blob/69598501ac7fc591878b9e29ca8e730768c4fa10/src/r-rig/install.sh#L331

It seems `--without-sysreqs` does nothing?

https://github.com/r-lib/rig/blob/74bb252854431a9630167ad7b6ed2c0b842a0105/src/linux.rs#L609-L633

**Comment by gaborcsardi** [comment]
Yeah, it would actually need to set 
```
PKG_SYSREQS="false"
```
because the default is `true` now in pak.

**Comment by eitsupi** [comment]
> Yeah, it would actually need to set
> 
> ```
> PKG_SYSREQS="false"
> ```
> 
> because the default is `true` now in pak.

Thanks for the quick reply, I didn't know the default values of `pak` had changed.

I question the need to opt out of it.
Because I often see behavior like apt installing pandoc when the latest pandoc is already installed from GitHub.
(Probably not a problem in the US, but Ubuntu's default mirror is very slow where I live, so I don't want to install anything with apt if at all possible.)

**Comment by gaborcsardi** [comment]
If you install pandoc from the deb package in their GH releases page, then pak should not update it.

**Comment by gaborcsardi** [comment]
This is what I see:
```
root@47d274b2de55:~# curl -LO https://github.com/jgm/pandoc/releases/download/3.1.8/pandoc-3.1.8-1-arm64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 31.8M  100 31.8M    0     0  19.9M      0  0:00:01  0:00:01 --:--:-- 35.8M
```

```
root@47d274b2de55:~# apt install ./pandoc-3.1.8-1-arm64.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'pandoc' instead of './pandoc-3.1.8-1-arm64.deb'
Suggested packages:
  texlive-latex-recommended texlive-xetex texlive-fonts-recommended
The following NEW packages will be installed:
  pandoc
0 upgraded, 1 newly installed, 0 to remove and 6 not upgraded.
Need to get 0 B/33.4 MB of archives.
After this operation, 162 MB of additional disk space will be used.
Get:1 /root/pandoc-3.1.8-1-arm64.deb pandoc arm64 3.1.8-1 [33.4 MB]
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package pandoc.
(Reading database ... 33237 files and directories currently installed.)
Preparing to unpack /root/pandoc-3.1.8-1-arm64.deb ...
Unpacking pandoc (3.1.8-1) ...
Setting up pandoc (3.1.8-1) ...
```

and then pak does not touch pandoc:

```
root@47d274b2de55:~# R -q -e 'pak::pkg_install("knitr?reinstall")'
> pak::pkg_install("knitr?reinstall")
✔ Loading metadata database ... done

→ Will install 1 package.
→ The package (895.05 kB) is cached.
+ knitr   1.44 [bld] + ✔ pandoc
✔ All system requirements are already installed.

ℹ No downloads are needed, 1 pkg (895.05 kB) is cached
ℹ Building knitr 1.44
✔ Built knitr 1.44 (318ms)
✔ Installed knitr 1.44  (43ms)
✔ 1 pkg + 4 deps: kept 4, added 1 [2.2s]
```

**Comment by eitsupi** [comment]
Thanks for letting me know that pak works well with the deb package.
I had created a simlink to the pandoc bundled with RStudio to make the pandoc command executable.
This is a special case and may not be of much concern, but I recall that cargo and rustc installed via rustup were also ignored.

**Comment by gaborcsardi** [comment]
Yes, system requirements use the packages of the distro. If you tend to install software other ways, then or indeed best to opt out.
