### ISSUE TITLE
rig (running on opensuse) does not find system installed R.

### ISSUE THREAD

**Issue by tckosvic** [r-lib/rig#192]
R installed by opensuse zypper.  R version 4.3.  rig does not find the installed R package as either user run or root run.

rig list     ---> shows nil
`(base) tom@mydesktop:~> rig list
* name  version  aliases
------------------------------------------
(base) tom@mydesktop:~> 
`
Does rig need some environment set up ?

**Comment by gaborcsardi** [comment]
Rig does not do anything about the built in R version, it doesn't even see it, so this is normal.

It creates its own R installations.
