### ISSUE TITLE
Link for latest release

### ISSUE THREAD

**Issue by hadley** [r-lib/rig#194]
You could link to this in the places in the readme where it's mentioned: https://github.com/r-lib/rig/releases/tag/latest

**Comment by gaborcsardi** [comment]
There is a link to the releases page, and the latest release (not the `latest` release, though) is always top. There is also a link to the latest release at the top right panel.

The `latest` release mainly exists for being able to download it programmatically.

**Comment by gaborcsardi** [comment]
I think the README now has links wherever it mentions the latest release.
