### ISSUE TITLE
Starting RStudio from the taskbar doesn't have correct user package library (Windows)

### ISSUE THREAD

**Issue by bdforbes** [r-lib/rig#201]
I'm trying to get started with `rig` on Windows with a clean slate. I installed `rig` first and then installed R 4.3.2, which created the user package library under `AppData/Local`. I've then installed RStudio, but when I start it up (from the taskbar) the first entry in `.libPaths()` is a new, empty library folder at `C:\Users\bdforbes\R`. 

When I start RStudio from `rig rstudio`, `.libPaths()` is set correctly. Is it the case that I will _always_ have to start RStudio from the command line in order for the correct behaviour to occur? I'm a bit confused about what the intention is for how `rig` is used, but it seems here that it could be quite easy to "mistakenly" start RStudio in the wrong way, and have inconsistencies in the available packages?

**Comment by gaborcsardi** [comment]
I don't know why this would be happening, rig is certainly not doing anything towards this behavior. 

First, check that you are indeed starting up the same version of R and you don't have two R installations on your system. E.g. run `R.home()` and see if they are the same.

Then check `Sys.getenv("R_LIBS_USER")` in both situations, and if they are different, see if you are setting this environment variable somewhere. 

You can also try just removing the empty `C:\Users\bdforbes\R` directory, if a directory does not exist, then it'll be removed from your `.Rprofile`.

**Comment by bdforbes** [comment]
Thanks, it was the `R_LIBS_USER` environment variable! I thought I had removed all traces of any previous R installation, but I forgot this one. After deleting it, I get the exact same behaviour whether I start RStudio from the taskbar or from `rig rstudio`. Thanks for the help!

**Comment by bdforbes** [comment]
Quick follow-up question: How is `R_LIBS_USER` actually getting set to the correct location even though it's not actually set in my user or system environment variables? I'm having a hard time tracing through all the different processes that occur when R starts. I can't find a reference to `C:\\Users\\bdforbes\\AppData\\Local/R/win-library/4.3` anywhere, but somehow that is populated in `R_LIBS_USER`. I can't see it in any `.Rprofile` or `.Renviron` files.

**Comment by gaborcsardi** [comment]
The default is set in `library/base/R/Rprofile` (within your R installation), in recent R versions via calling the `.expand_R_libs_env_var()` function. See
```
 ?R_LIBS_USER
```
for details.

**Comment by bdforbes** [comment]
Thanks, that's all making sense now.
