### ISSUE TITLE
Failed to  install R 4.2.1 

### ISSUE THREAD

**Issue by liliay** [r-lib/rig#209]
Dear rig dev(s) and users, 

First, thank you for this very promising tool ! 
I am trying to install the version 4.2.1 of R using the command line : 
`rig add 4.2.1`
Unfortunately, I get this error message : 

![image](https://github.com/r-lib/rig/assets/45742503/4866eb80-afde-4fad-a1f4-2aac3ff09c6e)

And this is what i am getting with the : 
`rig system detect-platform`
![image](https://github.com/r-lib/rig/assets/45742503/c41b7cd7-4182-490f-a5d4-5cb782e032f7)

Any idea on what is happening ? Did I forget to install something ?
Can't figure out what I can do to bypass this

Thanks in advance to anyone who could help with this !

**Comment by gaborcsardi** [comment]
We unfortunately don't support centos 8 any more.
