### ISSUE TITLE
`rig rstudio <release>` does not use correct R version

### ISSUE THREAD

**Issue by philiporlando** [r-lib/rig#210]
I have three different R versions installed via rig:

```
rig list
```
![image](https://github.com/r-lib/rig/assets/24445174/c02f2dc4-a2f5-4453-be07-e94425f39cee)

Running `rig rstudio 4.1.3` will open RStudio, but 4.3.1 is being used...
![image](https://github.com/r-lib/rig/assets/24445174/3258bf9f-cbc4-4f4e-93f6-092e46e6a730)

![image](https://github.com/r-lib/rig/assets/24445174/13a2748f-3ee4-4fed-a3c9-567c586862c3)

RStudio appears to be ignoring the R version specified by rig. Is it expected that the default R version overrides whichever version is passed to `rig rstudio`?

Changing the default R version does appear to be working when using `rig rstudio` though. So at least it's possible for me to launch RStudio using different R versions this way. 

Any input is appreciated. Thanks!

**Comment by gaborcsardi** [comment]
What version of rig? What version of RStudio?

**Comment by philiporlando** [comment]
My apologies. 

- rig 0.6.0
- RStudio/2023.12.1+402

**Comment by gaborcsardi** [comment]
I am fairly sure that this should be now fixed, the new release is coming very soon.

**Comment by philiporlando** [comment]
Thanks for the update. I'll try testing again once the new release is ready.

**Comment by philiporlando** [comment]
@gaborcsardi, confirming that rig 0.7.0 is working for me now. Thanks!
