### ISSUE TITLE
Completions for `zsh`

### ISSUE THREAD

**Issue by DanielRivasMD** [r-lib/rig#211]
Hi there,
Where can I find, or generate completions for `zsh`?
Much appreciated

**Comment by gaborcsardi** [comment]
zsh completions should work out of the box. What's your OS?

**Comment by DanielRivasMD** [comment]
Ok. I believe through `brew`. I will problably reinstall then. Thanks

**Comment by gaborcsardi** [comment]
Hopefully this is solved now. Please reopen if you still have problems.
