### ISSUE TITLE
how to switch to a different source for rig?

### ISSUE THREAD

**Issue by ssh352** [r-lib/rig#213]
Unfortunately the machine has a bad network connection, how can I set an alternate source for the deb package?

or is it possible to specify a local deb package for rig to use? Thanks!

```
❯ rig add release
[INFO] Running `sudo` for adding new R versions. This might need your password.
[INFO] Downloading https://cdn.posit.co/r/ubuntu-1804/pkgs/r-4.3.3_1_amd64.deb -> /tmp/rig/r-4.3.3_1_amd64.deb
[ERROR] HTTP error at https://cdn.posit.co/r/ubuntu-1804/pkgs/r-4.3.3_1_amd64.deb: HTTP status client error (403 Forbidden) for url (https://cdn.posit.co/r/ubuntu-1804/pkgs/r-4.3.3_1_amd64.deb)
```

**Comment by gaborcsardi** [comment]
See the message where the download will be saved (e.g. `/tmp/rig/r-4.3.3_1_amd64.deb` above), and put it there, then rig will pick it up.

I don't think these packages are available elsewhere, so there is no alternate source.

**Comment by ssh352** [comment]
> See the message where the download will be saved (e.g. `/tmp/rig/r-4.3.3_1_amd64.deb` above), and put it there, then rig will pick it up.
> 
> I don't think these packages are available elsewhere, so there is no alternate source.

```
❯ rig add release
[INFO] Running `sudo` for adding new R versions. This might need your password.
Password:
[INFO] Downloading https://cran.rstudio.com/bin/macosx/big-sur-x86_64/base/R-4.3.3-x86_64.pkg -> /tmp/rig/x86_64-R-4.3.3-x86_64.pkg
[INFO] Running installer
```
rig on Mac uses a different source, I'd try that source. Could you advise where the source could be changed?

I'd also try putting the deb file under /tmp/rig. 

Thanks!

**Comment by gaborcsardi** [comment]
You can't use cran.rstudio.com? That's an Amazon CDN, so that is quite bad.

You want to change the mirror macOS packages are downloaded from? You cannot do that currently. But you can do

```
rig add <URL>
```

**Comment by ssh352** [comment]
> You can't use cran.rstudio.com? That's an Amazon CDN, so that is quite bad.
> 
> You want to change the mirror macOS packages are downloaded from? You cannot do that currently. But you can do
> 
> ```
> rig add <URL>
> ```

I can't use https://cdn.posit.co. (ubuntu rig points to it) I can use cran.rstudio.com though (Mac rig points to it).

so I was thinking if I can use cran.rstudio.com on Linux too.

**Comment by gaborcsardi** [comment]
> I can't use [cdn.posit.co](https://cdn.posit.co/). (ubuntu rig points to it)

Why not?

> so I was thinking if I can use cran.rstudio.com on Linux too

Those files are not on cran.rstudio.com.

**Comment by ssh352** [comment]
> > I can't use [cdn.posit.co](https://cdn.posit.co/). (ubuntu rig points to it)
> 
> Why not?

I am not sure, here is the error
```
❯ wget "https://cdn.posit.co/r/ubuntu-1804/pkgs/r-4.3.3_1_amd64.deb"
--2024-03-05 22:30:36--  https://cdn.posit.co/r/ubuntu-1804/pkgs/r-4.3.3_1_amd64.deb
Resolving cdn.posit.co (cdn.posit.co)... 18.154.132.102, 18.154.132.60, 18.154.132.37, ...
Connecting to cdn.posit.co (cdn.posit.co)|18.154.132.102|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2024-03-05 22:30:37 ERROR 403: Forbidden.
```

> 
> > so I was thinking if I can use cran.rstudio.com on Linux too
> 
> Those files are not on cran.rstudio.com.

Ok Thanks. I'll probably just  install from source on ubuntu then.

**Comment by gaborcsardi** [comment]
Ubuntu 18.04 is not supported any more.
