### ISSUE TITLE
Can't run rig on gentoo

### ISSUE THREAD

**Issue by vlada79** [r-lib/rig#218]
vlada ~ $ rig system detect-platform
Detected platform:
Architecture: x86_64
OS:           linux
Distribution: gentoo
Version:      2.14
PPM support:  false
vlada ~ $ rig available
[ERROR] Cannot download JSON: HTTP status client error (404 Not Found) for url (https://api.r-hub.io/rversions/available/linux-gentoo-2.14/x86_64)

###

Please note that there is no 'version' per-se of gentoo as it is rolling release. I have no clue where it pulled 2.14 from.

**Comment by gaborcsardi** [comment]
We do not have R builds for Gentoo.
