### ISSUE TITLE
API calls failing for Fedora 40, prevents use of rig add

### ISSUE THREAD

**Issue by pj398** [r-lib/rig#233]
Hi, completely new to rig so may be missing something obvious, but after some trouble with packages not working well with R 4.4 I figured it was a good time to check out rig as I've heard it's a good way to manage multiple R installations.

Unfortunately, I can't get off the ground on Fedora 40 - using `rig available` or `rig add` just return the following error (e.g. for `rig add 4.3.3`):

```
[ERROR] Failed to resolve R version: Cannot download JSON: HTTP status client error (404 Not Found) for url (https://api.r-hub.io/rversions/resolve/4.3.3/linux-fedora-40/x86_64)
```

I'm guessing this is because the info for Fedora 40 hasn't been added yet on the server side? If so, is there a timeline on this? I could get around the error for `rig available` by trying `rig available --platform linux-fedora-39`  but can't see an equivalent to the platform argument for `rig add` that would allow me to work around it. Thanks.

**Comment by gaborcsardi** [comment]
We don't support Fedora 40 yet.

**Comment by gaborcsardi** [comment]
I started adding support for Fedora 40 here: https://github.com/rstudio/r-builds/pull/217

**Comment by gaborcsardi** [comment]
Fedora 40 is now supported, both on x86_64 and aarch64.
