### ISSUE TITLE
Integration with [Positron](https://github.com/posit-dev/positron)?

### ISSUE THREAD

**Issue by rkrug** [r-lib/rig#238]
Is there any integration of  [Positron](https://github.com/posit-dev/positron) planned, as it is currently with RStudio?

It would be great to start a project in Positron by selecting the R version from rig directly. .

**Comment by gaborcsardi** [comment]
Positron should detect all R versions installed by rig, and you can select the one you want to use within Positron in the top right corner:
![Screenshot 2024-07-10 at 10 28 28 AM](https://github.com/r-lib/rig/assets/660288/d9e110f9-5cf4-4ad1-a22d-4f1887b0f7e8)
![Screenshot 2024-07-10 at 10 29 03 AM](https://github.com/r-lib/rig/assets/660288/0fef9793-cbd5-4570-ba76-f78907c5a622)

Does that not work for you?

**Comment by rkrug** [comment]
Oh - they are hidden behind these "...". Thanks. Makes sense.

**Comment by gaborcsardi** [comment]
I am sorry, I don't follow. :(

What do you want rig to do? Or Positron needs to do something differently?

Something should be documented in rig? Or in Positron?

**Comment by jrosell** [comment]
I believe rig documentstion should include how to make positron only use the specific installed R versions you want.

**Comment by gaborcsardi** [comment]
I am not sure if that's up to rig to document, though. You can install multiple R builds without rig, especially easy on Windows or on Linux for the Posit R builds (e.g. following https://github.com/rstudio/r-builds#quick-installation).

It seems to me that to configure which R versions to use in Positron is something that Positron could document.

OTOH I am not sure if restricting Positron to a subset of installed R versions is something that many people need, though.

In any case, I can put in a note that all installed R versions should be available in Positron, and if that's not what you want, then you need to configure Positron.
