### ISSUE TITLE
Windows: `cannot determine installation directory`

### ISSUE THREAD

**Issue by t-kalinowski** [r-lib/rig#243]
On a fresh windows 11 image running in Parallels on macOS, I install rig and see: 

```
C:\Users\tomasz>rig add release
[INFO] Cleaning leftover registry entries
[INFO] Downloading https://cran.rstudio.com/bin/windows/base/R-4.4.1-win.exe -> C:\Users\tomasz\AppData\Local\Temp\rig\x86_64-R-4.4.1-win.exe
[INFO] Installing C:\Users\tomasz\AppData\Local\Temp\rig\x86_64-R-4.4.1-win.exe
[WARN] Cannot set CRAN mirror, cannot determine installation directory
[WARN] Cannot set up P3M, cannot determine installation directory
[WARN] Cannot install pak, cannot determine installation directory
```

It seems like R needs to have been previously installed for the correct registry key to exist. I wonder if this `open_subkey()` should be `create_subkey()`, so that the entry is auto-create dif the registry entry doesn't exist.
 

https://github.com/r-lib/rig/blob/140115c9b565167670cfc6f303e6c968c563db98/src/windows.rs#L1005

https://docs.rs/winreg/latest/winreg/reg_key/struct.RegKey.html#method.create_subkey

**Comment by gaborcsardi** [comment]
Is this arm64 macOS and arm64 Windows? rig does not support arm64 Windows currently.

Note that if you are running x86_64 R via the emulator, that has a lot of issues, including compilation failures and crashes.

**Comment by t-kalinowski** [comment]
Indeed, I'm on an arm mac. 

I'll try AWS instead (just need temporary access to a Windows machine)

**Comment by gaborcsardi** [comment]
I haven't tried this particular one, but in general this approach should work, I think: https://github.com/yrifl/synvm
