### ISSUE TITLE
Issue fixing permissions

### ISSUE THREAD

**Issue by eblchen** [r-lib/rig#252]
I get an error trying to switch R versions:
<img width="387" alt="Screenshot 2024-10-21 at 14 44 58" src="https://github.com/user-attachments/assets/ad0d2fd7-95c9-4036-b57e-e0029e3c07c8">
so tried using the command suggested:
<img width="636" alt="Screenshot 2024-10-21 at 14 43 56" src="https://github.com/user-attachments/assets/1621a6f1-dd71-4317-adcd-13e572893038">
but no luck fixing the original error (same error appears when trying to click on the drop down to switch R versions)

**Comment by eblchen** [comment]
<img width="569" alt="Screenshot 2024-10-21 at 14 52 06" src="https://github.com/user-attachments/assets/13006722-b8f3-41a7-9ef8-6f418c021d2b">

**Comment by gaborcsardi** [comment]
Are you an admin? What's the output of this?
```
id
```

**Comment by eblchen** [comment]
No but I have the admin password.
Output to `id`:
`uid=1128305577(echen) gid=25037 groups=25037,12(everyone),62(netaccounts),701(com.apple.sharepoint.group.1)`

**Comment by gaborcsardi** [comment]
If you don't to make your user an admin, but want to use the Rig app, you can try this:
```
sudo chmod -h 777 /Library/Frameworks/R.framework/Versions/Current
```

You might also need
```
sudo chmod 777 /Library/Frameworks/R.framework/Versions
```

I am not sure if these will keep working if you install new R versions, though.

**Comment by eblchen** [comment]
thank you will give this a go :)

**Comment by eblchen** [comment]
thank you looks like it is working now!
however in this folder /Library/Frameworks/R.framework/Versions I can see 3 versions of R: 
```
Versions echen$ ls
4.3-arm64	4.3-x86_64	4.4-arm64	Current
```
but can only see two in the drop down
<img width="358" alt="Screenshot 2024-10-22 at 14 23 45" src="https://github.com/user-attachments/assets/2e0ad7c9-0f02-4188-9c2b-528802382099">

**Comment by gaborcsardi** [comment]
Did you install them with rig? If not reinstall them with rig.

**Comment by eblchen** [comment]
Thank you so much for your help!
