### ISSUE TITLE
I can only have one version of R at a time

### ISSUE THREAD

**Issue by MarekGierlinski** [r-lib/rig#255]
I don't think this is an issue, it is probably something I don't understand, and I would appreciate some help.

I have 4.4.1 currently installed on my Macbook Pro with Sequoia 15.1:

```
> rig list
* name       version    aliases
------------------------------------------
* 4.4-arm64  (R 4.4.1)
```

I want to add 4.4.2 to have a choice between these two versions:

```
 > rig add 4.4.2
[INFO] Running `sudo` for adding new R versions. This might need your password.
[INFO] arm64-R-4.4.2-arm64.pkg is cached at /tmp/rig/arm64-R-4.4.2-arm64.pkg
[INFO] Running installer
[INFO] > installer: Package name is R 4.4.2 for macOS (ARM64)
[INFO] > installer: Installing at base path /
[INFO] > installer: The install was successful.
[INFO] Forgetting installed versions
[INFO] Fixing permissions
[INFO] Updating R-* quick links (as needed)
[INFO] Setting default CRAN mirror
[INFO] Installing pak for R 4.4-arm64 (if not installed yet)
```

But now, I have only 4.4.2 installed, and 4.4.1 seems to have disappeared:

```
> rig list
* name       version    aliases
------------------------------------------
* 4.4-arm64  (R 4.4.2)
```

If I do `rig add 4.4.1` now, it will remove 4.4.2 and keep only 4.4.1. Essentially, I can only have one version of R at a time.

Also, I started the MacOS menu bar app and it only shows one version at a time. 

I probably misunderstand how `rig` is supposed to work. I thought I would have a selection of installed versions to chose from. Specifically, I use Positron for my R projects and I expected to have a choice of R version in the dropdown menu at the top right. But it doesn't work that way.

**Comment by gaborcsardi** [comment]
See `rig install --help`:

```
  On macOS rig cannot add multiple R versions from the same minor branch.
  E.g. it is not possible to have R 4.1.1 and R 4.1.2 installed at the
  same time. Adding one of them will automatically remove the other.
```

**Comment by MarekGierlinski** [comment]
That explains it, thank you!

Does it mean I can have two major versions, like 4.4 and 4.5, at the same time?

**Comment by gaborcsardi** [comment]
> Does it mean I can have two major versions, like 4.4 and 4.5, at the same time?

Sure, that's the point. This is what I have:
```
❯ rig ls
* name        version    aliases
------------------------------------------
  3.4         (R 3.4.4)  
  3.5         (R 3.5.3)  
  3.6         (R 3.6.3)  
  4.0         (R 4.0.5)  
  4.1         (R 4.1.3)  
  4.1-arm64   (R 4.1.3)  
  4.2         (R 4.2.3)  
  4.2-arm64   (R 4.2.3)  
  4.3-arm64   (R 4.3.1)  
  4.3-x86_64  (R 4.3.1)  
* 4.4-arm64   (R 4.4.1)  release, next
  4.4-x86_64  (R 4.4.0)  
  4.5-arm64   (R 4.5.0)  
  4.5-x86_64  (R 4.5.0)  devel
```

(Major is the first number btw., minor is the second, so 4.4.x and 4.5.x are two minor versions.)

**Comment by MarekGierlinski** [comment]
Brilliant! Thanks again for your help.
