### ISSUE TITLE
R rig issue ERROR] command ["apt-get", "update"]

### ISSUE THREAD

**Issue by HHafida** [r-lib/rig#260]
Hi, 

I am trying to use Rig but I am facing an issue, I added the rig key to my configuration, hen to my repository, I installed the package
but when I try to do :  rig add 4.3.1 I have the following error [ERROR] command ["apt-get", "update"] exited with code 100.

Do you have please any idea on how to fix this ?

Thanks in advance

**Comment by HHafida** [comment]
Hello,

    OS: Ubuntu 22.04.5 LTS (Codename: Jammy)
    RIG Version: 0.7.0

rig add 4.3.1

[INFO] Downloading https://cdn.posit.co/r/ubuntu-2204/pkgs/r-4.3.1_1_amd64.deb -> /tmp/rig/r-4.3.1_1_amd64.deb
[INFO] Running "apt-get update"
[INFO] > Réception de :1 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
[INFO] > Atteint :2 http://fr.archive.ubuntu.com/ubuntu jammy InRelease
[INFO] > Atteint :3 https://download.docker.com/linux/ubuntu jammy InRelease
[INFO] > Réception de :4 http://fr.archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
[INFO] > Réception de :5 https://packages.microsoft.com/repos/code stable InRelease [3 590 B]
[INFO] > Réception de :6 http://security.ubuntu.com/ubuntu focal-security InRelease [128 kB]
[INFO] > Réception de :7 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3 626 B]
[INFO] > Atteint :8 https://dl.winehq.org/wine-builds/ubuntu jammy InRelease
[INFO] > Réception de :9 http://fr.archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
[INFO] > Ign :10 https://ppa.launchpadcontent.net/noobslab/apps/ubuntu jammy InRelease
[INFO] > Err :11 https://ppa.launchpadcontent.net/noobslab/apps/ubuntu jammy Release
[INFO] >   404  Not Found [IP : 185.125.190.80 443]
[INFO] > Atteint :12 https://srvwapt-pro.tranquil.it/entreprise/ubuntu/wapt-2.2 jammy InRelease
[INFO] > Réception de :13 https://dl.google.com/linux/chrome/deb stable InRelease [1 825 B]
[INFO] > Réception de :14 https://packages.microsoft.com/repos/code stable/main armhf Packages [18,3 kB]
[INFO] > Atteint :15 https://download.sublimetext.com apt/dev/ InRelease
[INFO] > Réception de :16 https://packages.microsoft.com/repos/code stable/main amd64 Packages [18,2 kB]
[INFO] > Réception de :17 https://packages.microsoft.com/repos/code stable/main arm64 Packages [18,3 kB]
[INFO] > Réception de :18 http://rig.r-pkg.org/deb rig InRelease
[INFO] > Réception de :19 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [1 967 kB]
[INFO] > Réception de :20 http://security.ubuntu.com/ubuntu jammy-security/main i386 Packages [569 kB]
[INFO] > Réception de :21 http://security.ubuntu.com/ubuntu jammy-security/main Translation-en [314 kB]
[INFO] > Réception de :22 http://security.ubuntu.com/ubuntu jammy-security/main amd64 DEP-11 Metadata [43,2 kB]
[INFO] > Réception de :23 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [2 638 kB]
[INFO] > Réception de :24 http://security.ubuntu.com/ubuntu jammy-security/restricted Translation-en [458 kB]
[INFO] > Réception de :25 http://fr.archive.ubuntu.com/ubuntu jammy-updates/main i386 Packages [731 kB]
[INFO] > Réception de :26 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 DEP-11 Metadata [208 B]
[INFO] > Réception de :27 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 DEP-11 Metadata [125 kB]
[INFO] > Réception de :28 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 DEP-11 Metadata [208 B]
[INFO] > Réception de :29 http://security.ubuntu.com/ubuntu focal-security/main amd64 DEP-11 Metadata [65,3 kB]
[INFO] > Réception de :30 http://fr.archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [2 192 kB]
[INFO] > Réception de :31 http://fr.archive.ubuntu.com/ubuntu jammy-updates/main amd64 DEP-11 Metadata [103 kB]
[INFO] > Réception de :32 http://fr.archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 DEP-11 Metadata [212 B]
[INFO] > Réception de :33 http://fr.archive.ubuntu.com/ubuntu jammy-updates/universe i386 Packages [753 kB]
[INFO] > Réception de :34 http://fr.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1 180 kB]
[INFO] > Réception de :35 http://fr.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 DEP-11 Metadata [356 kB]
[INFO] > Réception de :36 http://fr.archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 DEP-11 Metadata [940 B]
[INFO] > Réception de :37 http://fr.archive.ubuntu.com/ubuntu jammy-backports/main amd64 DEP-11 Metadata [5 332 B]
[INFO] > Réception de :38 http://fr.archive.ubuntu.com/ubuntu jammy-backports/restricted amd64 DEP-11 Metadata [212 B]
[INFO] > Réception de :39 http://fr.archive.ubuntu.com/ubuntu jammy-backports/universe amd64 DEP-11 Metadata [17,7 kB]
[INFO] > Réception de :40 http://fr.archive.ubuntu.com/ubuntu jammy-backports/multiverse amd64 DEP-11 Metadata [212 B]
[INFO] > Réception de :41 https://dl.google.com/linux/chrome/deb stable/main amd64 Packages [1 224 B]
[INFO] > Lecture des listes de paquets…
[INFO] > E: Le dépôt https://ppa.launchpadcontent.net/noobslab/apps/ubuntu jammy Release n'a pas de fichier Release.
[INFO] > W: https://dl.winehq.org/wine-builds/ubuntu/dists/jammy/InRelease: La clé est stockée dans l'ancien trousseau de clés trust.gpg (/etc/apt/trusted.gpg), voir la section DÉPRÉCATION dans apt-key(8) pour plus de détails.
[INFO] > W: https://ec127323-f6bc-46b3-a484-e552595bcaac:Qam3r2jznxPgPtjj@srvwapt-pro.tranquil.it/entreprise/ubuntu/wapt-2.2/dists/jammy/InRelease: La clé est stockée dans l'ancien trousseau de clés trust.gpg (/etc/apt/trusted.gpg), voir la section DÉPRÉCATION dans apt-key(8) pour plus de détails.
[ERROR] command ["apt-get", "update"] exited with code 100


Thanks in advance

**Comment by gaborcsardi** [comment]
> ```
> [INFO] > E: Le dépôt [ppa.launchpadcontent.net/noobslab/apps/ubuntu](https://ppa.launchpadcontent.net/noobslab/apps/ubuntu) jammy Release n'a pas de fichier Release.
> ```

Seems like your repository configuration has some errors. Try to fix that, so an `apt-get update` runs cleanly, without error.
