### ISSUE TITLE
Add support for ubuntu-based distros.

### ISSUE THREAD

**Issue by eliocamp** [r-lib/rig#34]
I'm running elementary OS 6.1 which is built on Ubuntu 20.04.3 LTS. Runing `rim add ` results in this error:

```
thread 'main' panicked at 'Unsupported distro: elementary 6.1, see rim list-supported', src/linux.rs:525:5
```

I don't know if there's a safe programmatic way to check if any particular distro is based on Ubuntu so the solution could be to allow the user to bypass the auto-discovery and specify the version to install (under their own risk, naturally). 

If it helps, my `/etc/os-release` looks like this:

```
NAME="elementary OS"
VERSION="6.1 Jólnir"
ID=elementary
ID_LIKE=ubuntu
PRETTY_NAME="elementary OS 6.1 Jólnir"
LOGO=distributor-logo
VERSION_ID="6.1"
HOME_URL="https://elementary.io/"
DOCUMENTATION_URL="https://elementary.io/docs/learning-the-basics"
SUPPORT_URL="https://elementary.io/support"
BUG_REPORT_URL="https://github.com/elementary/triage/issues/new"
PRIVACY_POLICY_URL="https://elementary.io/privacy-policy"
VERSION_CODENAME=jolnir
UBUNTU_CODENAME=focal
```

**Comment by gaborcsardi** [comment]
Yeah, being able to override the distro and the version would be natural, but in this case we can also auto-detect it.

**Comment by eliocamp** [comment]
I don't know what happened but I tried rig on a VM running elementary OS 7.1 and it fails to download: 

```
[ERROR] Failed to resolve R version: Cannot download JSON: HTTP status client error (404 Not Found) for url (https://api.r-hub.io/rversions/resolve/4.3.1/linux-elementary-7.1/x86_64)
```

It seems that for some reason it's failing to detect the correct ubuntu version. 

If it helps, here's /etc/os-release:

```
PRETTY_NAME="elementary OS 7.1 Horus"
NAME="elementary OS"
CPE_NAME="cpe:/o:elementary:elementary_os:7.1"
VERSION_ID="7.1"
VERSION="7.1 Horus"
VERSION_CODENAME=horus
ID=elementary
ID_LIKE="ubuntu debian"
HOME_URL="https://elementary.io/"
DOCUMENTATION_URL="https://elementary.io/docs/learning-the-basics"
SUPPORT_URL="https://elementary.io/support"
BUG_REPORT_URL="https://docs.elementary.io/contributor-guide/feedback/reporting-issues"
PRIVACY_POLICY_URL="https://elementary.io/privacy-policy"
UBUNTU_CODENAME=jammy
UBUNTU_PRETTY_NAME="Ubuntu 22.04.3 LTS"
UBUNTU_NAME="Ubuntu"
UBUNTU_VERSION_ID="22.04"
UBUNTU_VERSION="22.04.3 LTS (Jammy Jellyfish)"
UBUNTU_VERSION_CODENAME=jammy
```

(It seems that the `UBUNTU_*` variables changed name. I don't know if this is a new standard or something specific to my distro). 

Is there a scape hatch to manually force rig to use a particular distro?

**Comment by gaborcsardi** [comment]
> Linux: You can now set the `RIG_PLATFORM` environment variable to
> override the auto-detected Linux distriution. E.g.
> `RIG_PLATFORM=ubuntu-22.04` will force Ubuntu 22.04.

https://github.com/r-lib/rig/releases/tag/v0.6.0

**Comment by eliocamp** [comment]
Sorry, should've read the manual 😅

**Comment by eliocamp** [comment]
Huh, it seems that even with this envvar it still failing to look for the correct binary: 

```
elio@vm:~$ echo $RIG_PLATFORM
ubuntu-22.04
elio@vm:~$ rig system detect-platform
Detected platform:
Architecture: x86_64
OS:           linux
Distribution: ubuntu
Version:      22.04
PPM support:  true
PPM URL:      https://packagemanager.posit.co/cran/__linux__/jammy/latest
elio@vm:~$ rig add 4.3.1
[INFO] Running `sudo` for adding new R versions. This might need your password.
[ERROR] Failed to resolve R version: Cannot download JSON: HTTP status client error (404 Not Found) for url (https://api.r-hub.io/rversions/resolve/4.3.1/linux-elementary-7.1/x86_64)
```

**Comment by gaborcsardi** [comment]
It is probably not going through the sudo. Make sure it is set for th superuser, and please open an issue about this, if you can. Thanks!
