### ISSUE TITLE
`rig ls` lists additional directories that are not R versions

### ISSUE THREAD

**Issue by jemus42** [r-lib/rig#62]
Tested on Linux/Ubuntu 22.04 with `rig` 0.3.1 pre-release.

```sh
❯ rig --version
RIG -- The R Installation Manager 0.3.1
❯ pwd
/opt/R
❯ ls
4.1.3  4.2.0  current  etc
# current is a symlink to 4.2.0, as expected
❯ rig ls
4.1.3
4.2.0 (default)
etc
```

I personally use `/opt/R/etc` for global `Rprofile.site`/`Renviron.site` and symlink those into respective R version directories to set some options.
This workflow is not ideal, I know (haven't found a neater solution, but I wrote my helper scripts and, well, "it works").

In general I think it seems reasonable to expect `rig ls` to e.g. only show directories starting with a digit, e.g. matching `$\d` or `\d\.\d\.\d` etc.

In a previous version I also noticed `rim ls` listing a `.DS_Store` file on macOS, but this appears to not be an issue anymore.

**Comment by gaborcsardi** [comment]
Yeah, unfortunately some R versions, and thus directories are not of that form, e.g. there is `devel` for R-devel and `next` for R-next.

It makes sense to ignore `etc` on Linux, we can do that.

**Comment by gaborcsardi** [comment]
OTOH, we could also look for a `bin/R` file in the directory...
