### ISSUE TITLE
default library is not writeable

### ISSUE THREAD

**Issue by luceydav** [r-lib/rig#83]
Thank you for the library, It seems a lot like Pyenv, which has simplified a lot of problems for me. I installed with Homebrew instructions, but have two problems.

1/ When I try to install a package: 
When I choose "Install" in the RStudio Package tab, this pops up: "Would you like to create a personal library '/Users/davidlucey/Library/R/x86_64/4.2/library' to install packages into?". But then choosing "Yes" gives the same message again. Choosing "No" gives: "Unable to install packages (default library '/Users/davidlucey/Library/R/x86_64/4.2/library' is not writeable)". I did try running "rig system setup-user-lib", but that didn't fix it.

2/ Rig.app appears to start to launch, but then nothing happens and no error message.

sysname "Darwin" 
release "20.6.0" 
version "Darwin Kernel Version 20.6.0: Tue Apr 19 21:04:45 PDT 2022; root:xnu-7195.141.29~1/RELEASE_X86_64" 
nodename  "david.local" 
machine "x86_64"  
login  "root" 
user "davidlucey" 
 effective_user 
"davidlucey"

**Comment by gaborcsardi** [comment]
1. I think this is #80.
2. What's the output of `rig ls`?

**Comment by luceydav** [comment]
rig ls
4.2 (default)
4.3

I did run "rig system setup-user-lib", was I supposed to add a path or something there?

**Comment by gaborcsardi** [comment]
Maybe `/Users/davidlucey/Library/R/x86_64/4.2/library` but has the wrong permissions? Can you check that?

**Comment by luceydav** [comment]
.libPaths()
[1] "/Users/davidlucey/Library/R/x86_64/4.2/library"                
[2] "/Library/Frameworks/R.framework/Versions/4.2/Resources/library"

It definitely exists, I was assuming the Homebrew install would take care of permissions. I don't think I did anything to affect that.

**Comment by gaborcsardi** [comment]
Try starting it from a terminal to see if there are some error messages:
```
open /Applications/Rig.app
```

**Comment by luceydav** [comment]
open /Applications/Rig.app seems like it tries to open, then no message and returns to cursor. 

 /Applications/Rig.app/Contents/MacOS/Rig hangs and never opens until I break it.

**Comment by gaborcsardi** [comment]
Sorry for the silly question, but are you sure that the app is not on the menu bar? It is easy to miss it. This is how it looks for me (the `R 4.1` part):

<img width="318" alt="Screen Shot 2022-06-02 at 1 19 41 PM" src="https://user-images.githubusercontent.com/660288/171618299-ecae9eaf-b0b1-43dc-8b0b-613dfff17c5b.png">

I guess it probably also wouldn't show if your menu bar is full already?

**Comment by luceydav** [comment]
This is not a silly question! It is on the menu bar, I just misunderstood and was expecting to need to launch the app. Thank you so much for creating it.

**Comment by gaborcsardi** [comment]
Well, it is a menu bar app, so it lives there. :)
