### ISSUE TITLE
rig rm does not clean all stale registry entries

### ISSUE THREAD

**Issue by cderv** [r-lib/rig#86]
* `rig add 4.2.0` will install R and add to registry 
````
R-core
 > R <- Current Version and Install Path set to 4.2.0
   > 4.2.0 <- Current Version and Install Path set to 4.2.0
 > R64 <- Current Version and Install Path set to 4.2.0
   > 4.2.0 <- Current Version and Install Path set to 4.2.0
````

* `rig rm 4.2.0` will uninstall R and clean part of the registry which will be after 
```
R-core
 > R <- Current Version and Install Path set to 4.2.0
 > R64 <- Current Version and Install Path set to 4.2.0
```

So default version is sill set to the uninstall version. `rig system clean-registry` does not help (I guess this is what is called in the first place)

If we install several versions, and change default and then uninstall the one set as default, the default version in registry will still be the one uninstalled

* `rig add 4.2.0` is doing as describe above
* `rig add 4.1.2` will add 4.1.2 entry in registry
* `rig default 4.1.2` will modify the registry default version -> Current Version and Install Path are set to 4.1.2
* `rig rm 4.1.2` will uninstall and remove 4.1.2 from registry, but not from default R version where state will be
```
R-core
 > R <- Current Version and Install Path set to 4.1.2 which does not exists anymore 
   > 4.2.0 <- Current Version and Install Path set to 4.2.0
 > R64 <- Current Version and Install Path set to 4.1.2 which does not exists anymore 
   > 4.2.0 <- Current Version and Install Path set to 4.2.0
````
* `rig default 4.2.0` fix the problem

So it is possible to be in a state where the default version information is not the correct one. 
Found while trying to debug Quarto to find R installation when manage by `rig`

**Comment by gaborcsardi** [comment]
Yes, this is all true, and I am actually aware of it. OTOH it is not clear to me what rig should do in this case? Set a different version of rig as the default? Which one? Remove the default completely? That does not seem right, either.

**Comment by cderv** [comment]
right, not easy to know what should be done. But it feels off that a non existing version is kept as default, it is a wrong value in the registry for anyone who uses it. (like Quarto did for example). 

I think it would make sense to remove the default completely. `rig` is setting up some value it should probably unset it. 
Setting default version to be the greater one installed makes sense to me too. 

But maybe this is an edge case or I am missing some side effects.

**Comment by cderv** [comment]
> deletes R without running the uninstaller

Who deletes a program on Windows without an uninstaller using the Program Manager pane ?  :)
