### ISSUE TITLE
Installing R versions without message translations

### ISSUE THREAD

**Issue by mbojan** [r-lib/rig#88]
Is there an option (on Windows) to use `rig` to install R versions without message translations?

**Comment by gaborcsardi** [comment]
No, there is no way currently. This is a pretty similar issue to not creating a desktop icon, in that we would need to supply a parameter to the installer, once I look into that, I can consider this as well. 

Btw. is your goal using R in English on a computer with a different locale?

**Comment by mbojan** [comment]
> No, there is no way currently. This is a pretty similar issue to not creating a desktop icon, in that we would need to supply a parameter to the installer, once I look into that, I can consider this as well.

Sounds great!


> Btw. is your goal using R in English on a computer with a different locale?

Yes. Exactly that.

**Comment by gaborcsardi** [comment]
I guess we could also just remove the translations after the installation. I bet the effect is the same.

**Comment by mbojan** [comment]
I never tried just removing. I don't think there is an option/configuration to start R disregarding them either. Is it a challenge to customize options with which `rig` launches the R Windows installer? At the same time, perhaps I can simply set `LANGUAGE = "en"` or use `Sys.setlanguage()` (https://stat.ethz.ch/R-manual/R-patched/library/base/html/gettext.html), I never thought of that because I always choose not to install the translations.

**Comment by gaborcsardi** [comment]
Yeah, it is possible to specify the components to install, but AFAICT it is not possible to say "install everything that installed by default, except the translations". And over the years the names of the components have changes slightly, and they can also change in the future, so it is a bit messy to specify the components to install.

**Comment by gaborcsardi** [comment]
OTOH it is ok to specify non-existing components, so we can probably do this.
