### ISSUE TITLE
Windows: do not create desktop icon

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/rig#89]
IDK if it is worth having an option for this. Does anyone wants desktop icons for all their programs in 2022?

**Comment by mbojan** [comment]
I would love the no-icons default.

Isn't the desktopiconsforallappsomania a sister syndrome to browsertabclosingophobia?

**Comment by gaborcsardi** [comment]
Fixed in 5ac493fec981e4c8434adefa842bc7d8081d2be7
